import { SceneConfig, SceneConfigSchema } from './schema';

export interface PresetDefinition {
  id: string;
  name: string;
  description: string;
  category: string;
  config: SceneConfig;
}

export const PRESETS: Record<string, PresetDefinition> = {
  minimal: {
    id: 'minimal',
    name: 'Minimal Light',
    description: 'Clean, understated light mode with high-contrast dots and cobalt highlights.',
    category: 'General',
    config: SceneConfigSchema.parse({
      metadata: { title: 'Minimal Light' },
      appearance: {
        dark: 0,
        baseColor: [1, 1, 1],
        markerColor: [0.0, 0.27, 0.96],
        glowColor: [1, 1, 1],
        arcColor: [0.0, 0.27, 0.96],
        diffuse: 1.2,
        mapSamples: 16000,
        mapBrightness: 6,
        mapBaseBrightness: 0,
      },
      transform: { phi: 0, theta: 0.2, autoRotate: true, autoRotateSpeed: 0.003 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'Minimal · Clean WebGL · Orblob · ' },
      markers: [
        { id: 'sf', name: 'San Francisco', location: [37.77, -122.42], size: 0.035, color: [0.0, 0.27, 0.96], visible: true },
        { id: 'london', name: 'London', location: [51.51, -0.13], size: 0.035, color: [0.0, 0.27, 0.96], visible: true },
      ],
      arcs: [
        { id: 'sf-london', name: 'SF to London', from: [37.77, -122.42], to: [51.51, -0.13], color: [0.0, 0.27, 0.96], width: 0.5, height: 0.3, visible: true },
      ],
      labels: [
        { id: 'l-sf', targetType: 'marker', targetId: 'sf', text: 'SF Node', style: 'pill', visible: true },
      ],
    }),
  },
  'dark-space': {
    id: 'dark-space',
    name: 'Dark Space',
    description: 'Deep midnight obsidian backdrop with glowing cyan-blue planetary dots.',
    category: 'Cosmic',
    config: SceneConfigSchema.parse({
      metadata: { title: 'Dark Space' },
      appearance: {
        dark: 1,
        baseColor: [0.3, 0.3, 0.4],
        markerColor: [0.2, 0.7, 1],
        glowColor: [0.1, 0.2, 0.5],
        arcColor: [0.2, 0.8, 1],
        diffuse: 1.6,
        mapSamples: 24000,
        mapBrightness: 12,
        mapBaseBrightness: 0.05,
      },
      transform: { phi: 1.2, theta: 0.25, autoRotate: true, autoRotateSpeed: 0.004 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'Orbital Horizon · Deep Space · 3D WebGL · ' },
      markers: [
        { id: 'tokyo', name: 'Tokyo', location: [35.68, 139.69], size: 0.04, color: [0.2, 0.8, 1], pulse: true, visible: true },
        { id: 'sydney', name: 'Sydney', location: [-33.87, 151.21], size: 0.035, color: [0.2, 0.8, 1], visible: true },
      ],
      arcs: [
        { id: 'tokyo-sydney', name: 'Tokyo → Sydney', from: [35.68, 139.69], to: [-33.87, 151.21], color: [0.3, 0.9, 1], width: 0.6, height: 0.35, visible: true },
      ],
      labels: [
        { id: 'l-tokyo', targetType: 'marker', targetId: 'tokyo', text: 'Tokyo Orbit', subtitle: 'Ground Station', style: 'card', visible: true },
      ],
    }),
  },
  editorial: {
    id: 'editorial',
    name: 'Editorial Swiss',
    description: 'Disciplined monochrome with ultra-crisp typography and warm slate neutrals.',
    category: 'Design',
    config: SceneConfigSchema.parse({
      metadata: { title: 'Editorial Swiss' },
      appearance: {
        dark: 0,
        baseColor: [0.95, 0.95, 0.95],
        markerColor: [0.1, 0.1, 0.15],
        glowColor: [0.9, 0.9, 0.9],
        arcColor: [0.1, 0.1, 0.15],
        diffuse: 1.1,
        mapSamples: 18000,
        mapBrightness: 8,
        mapBaseBrightness: 0.02,
      },
      transform: { phi: 0.5, theta: 0.15, autoRotate: true, autoRotateSpeed: 0.002 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'Typographic Precision · Swiss Grid · ' },
      markers: [
        { id: 'paris', name: 'Paris', location: [48.85, 2.35], size: 0.035, color: [0.1, 0.1, 0.15], visible: true },
        { id: 'berlin', name: 'Berlin', location: [52.52, 13.4], size: 0.035, color: [0.1, 0.1, 0.15], visible: true },
      ],
      arcs: [
        { id: 'paris-berlin', name: 'Paris → Berlin', from: [48.85, 2.35], to: [52.52, 13.4], color: [0.1, 0.1, 0.15], width: 0.4, height: 0.2, visible: true },
      ],
      labels: [],
    }),
  },
  enterprise: {
    id: 'enterprise',
    name: 'Enterprise Cloud',
    description: 'Global infrastructure topology with multi-region datacenter links.',
    category: 'Business',
    config: SceneConfigSchema.parse({
      metadata: { title: 'Enterprise Cloud' },
      appearance: {
        dark: 1,
        baseColor: [0.1, 0.15, 0.25],
        markerColor: [0, 0.55, 1],
        glowColor: [0.05, 0.2, 0.4],
        arcColor: [0.1, 0.7, 1],
        diffuse: 1.5,
        mapSamples: 20000,
        mapBrightness: 10,
        mapBaseBrightness: 0.05,
      },
      transform: { phi: 3.5, theta: 0.3, autoRotate: true, autoRotateSpeed: 0.003 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'Multi-Region WAN · 99.999% SLA · Mesh Network · ' },
      markers: [
        { id: 'us-east', name: 'us-east (Virginia)', location: [39.04, -77.48], size: 0.04, color: [0, 0.6, 1], pulse: true, visible: true },
        { id: 'eu-central', name: 'eu-central (Frankfurt)', location: [50.11, 8.68], size: 0.04, color: [0, 0.8, 0.4], pulse: true, visible: true },
        { id: 'ap-northeast', name: 'ap-northeast (Tokyo)', location: [35.68, 139.69], size: 0.04, color: [1, 0.6, 0], pulse: true, visible: true },
        { id: 'sa-east', name: 'sa-east (São Paulo)', location: [-23.55, -46.63], size: 0.035, color: [0.8, 0.2, 1], visible: true },
      ],
      arcs: [
        { id: 'transatlantic', name: 'Backbone Transatlantic', from: [39.04, -77.48], to: [50.11, 8.68], color: [0, 0.8, 1], width: 0.8, height: 0.35, visible: true },
        { id: 'transpacific', name: 'Backbone Transpacific', from: [39.04, -77.48], to: [35.68, 139.69], color: [1, 0.6, 0.2], width: 0.8, height: 0.4, visible: true },
        { id: 'pan-americas', name: 'Pan-Americas Trunk', from: [39.04, -77.48], to: [-23.55, -46.63], color: [0.8, 0.3, 1], width: 0.6, height: 0.25, visible: true },
      ],
      labels: [
        { id: 'l-us', targetType: 'marker', targetId: 'us-east', text: 'us-east-1', subtitle: '42ms RTT', style: 'pill', visible: true },
        { id: 'l-eu', targetType: 'marker', targetId: 'eu-central', text: 'eu-central-1', subtitle: 'Primary Europe', style: 'pill', visible: true },
      ],
    }),
  },
  satellite: {
    id: 'satellite',
    name: 'Satellite Constellation',
    description: 'High-altitude telemetry with LEO ground station tracking.',
    category: 'Aerospace',
    config: SceneConfigSchema.parse({
      metadata: { title: 'Satellite Constellation' },
      appearance: {
        dark: 1,
        baseColor: [0.08, 0.12, 0.2],
        markerColor: [0.2, 1, 0.6],
        glowColor: [0.1, 0.4, 0.6],
        arcColor: [0.2, 1, 0.6],
        diffuse: 1.8,
        mapSamples: 22000,
        mapBrightness: 11,
        mapBaseBrightness: 0.04,
      },
      transform: { phi: 2.1, theta: 0.4, autoRotate: true, autoRotateSpeed: 0.005 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'LEO Sat-Track · Ground Station Uplink · ' },
      markers: [
        { id: 'svalbard', name: 'Svalbard Sat-Station', location: [78.22, 15.65], size: 0.045, color: [0.2, 1, 0.6], pulse: true, visible: true },
        { id: 'singapore', name: 'Singapore Station', location: [1.35, 103.82], size: 0.035, color: [0.2, 1, 0.6], visible: true },
        { id: 'houston', name: 'Houston Mission Control', location: [29.76, -95.36], size: 0.04, color: [1, 0.8, 0.2], visible: true },
      ],
      arcs: [
        { id: 'sat-arc-1', name: 'Polar Telemetry', from: [78.22, 15.65], to: [29.76, -95.36], color: [0.2, 1, 0.6], width: 0.7, height: 0.45, visible: true },
      ],
      labels: [
        { id: 'l-sat1', targetType: 'marker', targetId: 'svalbard', text: 'Svalbard Uplink', subtitle: '78° N Polar', style: 'card', visible: true },
      ],
    }),
  },
  network: {
    id: 'network',
    name: 'Mesh Network',
    description: 'High-density multi-hop network nodes connected across five continents.',
    category: 'Technology',
    config: SceneConfigSchema.parse({
      metadata: { title: 'Mesh Network' },
      appearance: {
        dark: 1,
        baseColor: [0.15, 0.15, 0.22],
        markerColor: [0.3, 0.6, 1],
        glowColor: [0.2, 0.3, 0.6],
        arcColor: [0.4, 0.7, 1],
        diffuse: 1.4,
        mapSamples: 18000,
        mapBrightness: 9,
        mapBaseBrightness: 0.03,
      },
      transform: { phi: 0.8, theta: 0.2, autoRotate: true, autoRotateSpeed: 0.003 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'Decentralized Protocol · Peer Mesh · ' },
      markers: [
        { id: 'nyc', name: 'NYC', location: [40.71, -74.01], size: 0.035, color: [0.3, 0.6, 1], visible: true },
        { id: 'london', name: 'London', location: [51.51, -0.13], size: 0.035, color: [0.3, 0.6, 1], visible: true },
        { id: 'dubai', name: 'Dubai', location: [25.2, 55.27], size: 0.035, color: [0.3, 0.6, 1], visible: true },
        { id: 'singapore', name: 'Singapore', location: [1.35, 103.82], size: 0.035, color: [0.3, 0.6, 1], visible: true },
        { id: 'tokyo', name: 'Tokyo', location: [35.68, 139.69], size: 0.035, color: [0.3, 0.6, 1], visible: true },
      ],
      arcs: [
        { id: 'nyc-lon', name: 'NYC-London', from: [40.71, -74.01], to: [51.51, -0.13], color: [0.4, 0.7, 1], width: 0.5, height: 0.25, visible: true },
        { id: 'lon-dxb', name: 'London-Dubai', from: [51.51, -0.13], to: [25.2, 55.27], color: [0.4, 0.7, 1], width: 0.5, height: 0.25, visible: true },
        { id: 'dxb-sin', name: 'Dubai-Singapore', from: [25.2, 55.27], to: [1.35, 103.82], color: [0.4, 0.7, 1], width: 0.5, height: 0.25, visible: true },
        { id: 'sin-tyo', name: 'Singapore-Tokyo', from: [1.35, 103.82], to: [35.68, 139.69], color: [0.4, 0.7, 1], width: 0.5, height: 0.25, visible: true },
      ],
      labels: [],
    }),
  },
  'data-viz': {
    id: 'data-viz',
    name: 'Data Heatmap',
    description: 'High-density point sampling optimized for demographic or metrics visualization.',
    category: 'Analytics',
    config: SceneConfigSchema.parse({
      metadata: { title: 'Data Heatmap' },
      appearance: {
        dark: 0,
        baseColor: [1, 1, 1],
        markerColor: [1, 0.25, 0.2],
        glowColor: [0.95, 0.95, 0.95],
        arcColor: [1, 0.4, 0.2],
        diffuse: 1.3,
        mapSamples: 28000,
        mapBrightness: 8,
        mapBaseBrightness: 0.01,
      },
      transform: { phi: 1.5, theta: 0.1, autoRotate: true, autoRotateSpeed: 0.002 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'Global Analytics · 28K Sample Points · ' },
      markers: [
        { id: 'm1', name: 'Region Alpha', location: [45.0, 9.0], size: 0.05, color: [1, 0.2, 0.2], pulse: true, visible: true },
        { id: 'm2', name: 'Region Beta', location: [35.0, 115.0], size: 0.06, color: [1, 0.4, 0.1], pulse: true, visible: true },
        { id: 'm3', name: 'Region Gamma', location: [28.0, 77.0], size: 0.055, color: [1, 0.3, 0.15], pulse: true, visible: true },
      ],
      arcs: [],
      labels: [
        { id: 'l1', targetType: 'marker', targetId: 'm1', text: '1.4M Events/sec', style: 'card', visible: true },
      ],
    }),
  },
  travel: {
    id: 'travel',
    name: 'World Voyager',
    description: 'Scenic travel itinerary tracing iconic cultural capitals across the world.',
    category: 'Lifestyle',
    config: SceneConfigSchema.parse({
      metadata: { title: 'World Voyager' },
      appearance: {
        dark: 0,
        baseColor: [0.98, 0.96, 0.92],
        markerColor: [0.85, 0.35, 0.15],
        glowColor: [0.95, 0.9, 0.85],
        arcColor: [0.85, 0.4, 0.2],
        diffuse: 1.25,
        mapSamples: 16000,
        mapBrightness: 7,
        mapBaseBrightness: 0.02,
      },
      transform: { phi: 0, theta: 0.25, autoRotate: true, autoRotateSpeed: 0.003 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'World Traveler · Discovery · Grand Tour · ' },
      markers: [
        { id: 'rome', name: 'Rome', location: [41.9, 12.5], size: 0.035, color: [0.85, 0.35, 0.15], visible: true },
        { id: 'cairo', name: 'Cairo', location: [30.04, 31.23], size: 0.035, color: [0.85, 0.35, 0.15], visible: true },
        { id: 'kyoto', name: 'Kyoto', location: [35.01, 135.77], size: 0.035, color: [0.85, 0.35, 0.15], visible: true },
      ],
      arcs: [
        { id: 'rome-cairo', name: 'Rome to Cairo', from: [41.9, 12.5], to: [30.04, 31.23], color: [0.85, 0.4, 0.2], width: 0.5, height: 0.2, visible: true },
        { id: 'cairo-kyoto', name: 'Cairo to Kyoto', from: [30.04, 31.23], to: [35.01, 135.77], color: [0.85, 0.4, 0.2], width: 0.6, height: 0.4, visible: true },
      ],
      labels: [
        { id: 'l-rome', targetType: 'marker', targetId: 'rome', text: 'Roma Antiqua', style: 'pill', visible: true },
      ],
    }),
  },
  'flight-tracker': {
    id: 'flight-tracker',
    name: 'Aviation Corridors',
    description: 'Intercontinental high-altitude long-haul flight path visualization.',
    category: 'Transportation',
    config: SceneConfigSchema.parse({
      metadata: { title: 'Aviation Corridors' },
      appearance: {
        dark: 1,
        baseColor: [0.1, 0.12, 0.18],
        markerColor: [1, 0.8, 0.1],
        glowColor: [0.15, 0.2, 0.3],
        arcColor: [1, 0.85, 0.2],
        diffuse: 1.5,
        mapSamples: 20000,
        mapBrightness: 10,
        mapBaseBrightness: 0.04,
      },
      transform: { phi: 5.2, theta: 0.35, autoRotate: true, autoRotateSpeed: 0.004 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'Live Air Traffic · Great Circle Routes · ' },
      markers: [
        { id: 'lhr', name: 'London Heathrow (LHR)', location: [51.47, -0.45], size: 0.04, color: [1, 0.8, 0.1], pulse: true, visible: true },
        { id: 'jfk', name: 'New York JFK', location: [40.64, -73.78], size: 0.04, color: [1, 0.8, 0.1], pulse: true, visible: true },
        { id: 'hnd', name: 'Tokyo Haneda (HND)', location: [35.55, 139.78], size: 0.04, color: [1, 0.8, 0.1], pulse: true, visible: true },
      ],
      arcs: [
        { id: 'ba178', name: 'BA178 (JFK → LHR)', from: [40.64, -73.78], to: [51.47, -0.45], color: [1, 0.85, 0.2], width: 0.7, height: 0.32, visible: true },
        { id: 'nh109', name: 'NH109 (JFK → HND)', from: [40.64, -73.78], to: [35.55, 139.78], color: [1, 0.7, 0.1], width: 0.8, height: 0.45, visible: true },
      ],
      labels: [
        { id: 'l-jfk', targetType: 'marker', targetId: 'jfk', text: 'KJFK Terminal 4', subtitle: 'FL380 Outbound', style: 'card', visible: true },
      ],
    }),
  },
  weather: {
    id: 'weather',
    name: 'Meteorological Radar',
    description: 'Atmospheric pressure systems and ocean current observation palette.',
    category: 'Science',
    config: SceneConfigSchema.parse({
      metadata: { title: 'Meteorological Radar' },
      appearance: {
        dark: 1,
        baseColor: [0.05, 0.15, 0.2],
        markerColor: [0.2, 0.9, 0.8],
        glowColor: [0.1, 0.5, 0.7],
        arcColor: [0.3, 0.95, 0.85],
        diffuse: 1.7,
        mapSamples: 22000,
        mapBrightness: 12,
        mapBaseBrightness: 0.08,
      },
      transform: { phi: 1.8, theta: 0.2, autoRotate: true, autoRotateSpeed: 0.003 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'Atmospheric Pressure · Ocean Gyres · Isobars · ' },
      markers: [
        { id: 'cyclone', name: 'Depression Center', location: [18.5, 88.0], size: 0.06, color: [0.2, 0.9, 0.8], pulse: true, visible: true },
      ],
      arcs: [],
      labels: [
        { id: 'l-cyclone', targetType: 'marker', targetId: 'cyclone', text: 'Low 984 hPa', subtitle: 'Category 3 Track', style: 'card', visible: true },
      ],
    }),
  },
  'ai-network': {
    id: 'ai-network',
    name: 'AI Neural Gateway',
    description: 'Autonomous agent clusters and multi-modal neural compute distribution.',
    category: 'Technology',
    config: SceneConfigSchema.parse({
      metadata: { title: 'AI Neural Gateway' },
      appearance: {
        dark: 1,
        baseColor: [0.12, 0.08, 0.25],
        markerColor: [0.8, 0.3, 1],
        glowColor: [0.4, 0.1, 0.7],
        arcColor: [0.9, 0.4, 1],
        diffuse: 1.6,
        mapSamples: 24000,
        mapBrightness: 13,
        mapBaseBrightness: 0.04,
      },
      transform: { phi: 4.2, theta: 0.28, autoRotate: true, autoRotateSpeed: 0.004 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'Neural Matrix · Agentic Swarm · Distributed Weights · ' },
      markers: [
        { id: 'cluster-sf', name: 'Core Frontier Cluster', location: [37.77, -122.42], size: 0.045, color: [0.9, 0.3, 1], pulse: true, visible: true },
        { id: 'cluster-lon', name: 'DeepMind Node', location: [51.51, -0.13], size: 0.04, color: [0.7, 0.3, 1], pulse: true, visible: true },
        { id: 'cluster-sin', name: 'APAC Inference Mesh', location: [1.35, 103.82], size: 0.04, color: [0.8, 0.4, 1], visible: true },
      ],
      arcs: [
        { id: 'arc-synapse', name: 'Synaptic Bus', from: [37.77, -122.42], to: [51.51, -0.13], color: [0.9, 0.4, 1], width: 0.8, height: 0.35, visible: true },
        { id: 'arc-inference', name: 'Inference Feed', from: [51.51, -0.13], to: [1.35, 103.82], color: [0.8, 0.3, 1], width: 0.7, height: 0.3, visible: true },
      ],
      labels: [
        { id: 'l-sf-ai', targetType: 'marker', targetId: 'cluster-sf', text: '100k H100 Cluster', subtitle: '4.2 PFLOPS', style: 'card', visible: true },
      ],
    }),
  },
  monochrome: {
    id: 'monochrome',
    name: 'Pure Monochrome',
    description: 'Strict 1-bit style high-contrast aesthetic with deep black and stark white.',
    category: 'Design',
    config: SceneConfigSchema.parse({
      metadata: { title: 'Pure Monochrome' },
      appearance: {
        dark: 1,
        baseColor: [0, 0, 0],
        markerColor: [1, 1, 1],
        glowColor: [0.3, 0.3, 0.3],
        arcColor: [1, 1, 1],
        diffuse: 1.0,
        mapSamples: 20000,
        mapBrightness: 14,
        mapBaseBrightness: 0,
      },
      transform: { phi: 0, theta: 0.2, autoRotate: true, autoRotateSpeed: 0.003 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'Binary Form · 1-Bit Dot Matrix · Pure Contrast · ' },
      markers: [
        { id: 'm-mono1', name: 'Node A', location: [40.71, -74.01], size: 0.035, color: [1, 1, 1], visible: true },
        { id: 'm-mono2', name: 'Node B', location: [35.68, 139.69], size: 0.035, color: [1, 1, 1], visible: true },
      ],
      arcs: [
        { id: 'mono-arc', name: 'Binary Bridge', from: [40.71, -74.01], to: [35.68, 139.69], color: [1, 1, 1], width: 0.5, height: 0.3, visible: true },
      ],
      labels: [],
    }),
  },
  blueprint: {
    id: 'blueprint',
    name: 'Cyan Blueprint',
    description: 'Architectural draft grid in cyan and deep navy engineering blue.',
    category: 'Architecture',
    config: SceneConfigSchema.parse({
      metadata: { title: 'Cyan Blueprint' },
      appearance: {
        dark: 1,
        baseColor: [0.04, 0.1, 0.22],
        markerColor: [0, 0.9, 1],
        glowColor: [0.05, 0.3, 0.6],
        arcColor: [0, 0.9, 1],
        diffuse: 1.5,
        mapSamples: 24000,
        mapBrightness: 11,
        mapBaseBrightness: 0.05,
      },
      transform: { phi: 0.9, theta: 0.25, autoRotate: true, autoRotateSpeed: 0.003 },
      atmosphere: { showOrbitRing: true, orbitRingText: 'Architectural Spec · Cyan Coordinate Grid · ' },
      markers: [
        { id: 'bp-1', name: 'Datum 01', location: [51.51, -0.13], size: 0.04, color: [0, 0.9, 1], pulse: true, visible: true },
        { id: 'bp-2', name: 'Datum 02', location: [37.77, -122.42], size: 0.04, color: [0, 0.9, 1], visible: true },
      ],
      arcs: [
        { id: 'bp-arc', name: 'Vector 01-02', from: [51.51, -0.13], to: [37.77, -122.42], color: [0, 0.9, 1], width: 0.6, height: 0.35, visible: true },
      ],
      labels: [
        { id: 'l-bp', targetType: 'marker', targetId: 'bp-1', text: 'Datum Zero (51°N)', style: 'pill', visible: true },
      ],
    }),
  },
};
